sonar.projectKey=MediCare
sonar.projectName=MediCare
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, **/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=admin
